añadiendo proyecto Blask
python-spain/hacktoberfestES pull request #7
Opened 2020-10-04 16:22 UTC by zerasul

Hola; he añadido el proyecto de blask.

Pero creo que mi editor ha tocado algo del formateo.

En principio solo he añadido el proyecto de Blask.

2020-10-04 17:35 UTC, cmaureir requested changes
@zerasul debes tener alguna herramienta de formato automático o algo, porque has modificado todo el archivo. Podrías agregar solo la parte del proyecto?

2020-10-05 08:48 UTC, zerasul commented
Hola; acabo de actualizar el fichero. Ya debería de mostrarse correctamente.

Un saludo.

2020-10-05 10:52 UTC, cmaureir approved these changes

2020-10-05 10:52 UTC, merged

2020-10-05 10:53 UTC, cmaureir commented
Gracias @zerasul :)